apiVersion: apps/v1
kind: Deployment
metadata:
  name: dns-attacker
spec:
  replicas: 1  # Adjust the number of replicas as needed
  selector:
    matchLabels:
      app: dns-attacker
  template:
    metadata:
      labels:
        app: dns-attacker
    spec:
      containers:
        - name: dns-attacker
          image: dns_attacker
          imagePullPolicy: Never
          resources:
            limits:
              memory: "256Mi"
              cpu: "0.5"
            requests:
              memory: "128Mi"
              cpu: "0.25"
