FROM ubuntu:latest
LABEL authors="souri"

# Set the working directory inside the container
WORKDIR /app

# Update the package list and install necessary packages
RUN apt-get update && \
    apt-get install -y python3 python3-pip

# Copy the Python script into the container
COPY dns_gatekeeper.py .

COPY requirements.txt .

COPY zones/* ./zones/

RUN pip install -r requirements.txt

# Expose the port that the Python server will run on
EXPOSE 53

EXPOSE 31110

# Command to run the Python server
CMD ["python3", "dns_gatekeeper.py"]