apiVersion: v1
kind: Service
metadata:
  name: dns-gatekeeper
  namespace: default
spec:
  selector:
    app: dns-gatekeeper
  type: ClusterIP
  ports:
    - name: udp
      port: 53
      targetPort: 53
      protocol: UDP