apiVersion: v1
kind: Service
metadata:
  labels:
    helm.sh/chart: ingress-nginx-3.10.1
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/instance: ingress-nginx
    app.kubernetes.io/version: 0.41.2
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: udp-controller
  name: ingress-nginx-udp-controller
  namespace: kube-system
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  ports:
    - name: udp
      port: 31110
      protocol: UDP
      targetPort: 31110
      nodePort: 31110
  selector:
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/instance: ingress-nginx
    app.kubernetes.io/component: udp-controller