apiVersion: v1
kind: Service
metadata:
  name: dns-service-primary
  namespace: default
spec:
  selector:
    app: dns-server-primary
  type: ClusterIP
  ports:
    - name: udp
      port: 31111
      targetPort: 31111
      protocol: UDP